In [1]:
import numpy as np
import copy

In [2]:
def inputMatrix():
    n=int(input())
    a = np.array([[float(input()) for j in range(n)] for i in range(n)])
    b=np.eye(n)
    #nhap ma tran
    return a,b,n

In [3]:
def determinant_recursive(A, total=0):
    # Section 1: store indices in list for row referencing
    indices = list(range(len(A)))
     
    # Section 2: when at 2x2 submatrices recursive calls end
    if len(A) == 2 and len(A[0]) == 2:
        val = A[0][0] * A[1][1] - A[1][0] * A[0][1]
        return val
 
    # Section 3: define submatrix for focus column and 
    #      call this function
    for fc in indices: # A) for each focus column, ...
        # find the submatrix ...
        As = copy.deepcopy(A) # B) make a copy, and ...
        As = As[1:] # ... C) remove the first row
        height = len(As) # D) 
 
        for i in range(height): 
            # E) for each remaining row of submatrix ...
            #     remove the focus column elements
            As[i] = As[i][0:fc] + As[i][fc+1:] 
 
        sign = (-1) ** (fc % 2) # F) 
        # G) pass submatrix recursively
        sub_det = determinant_recursive(As)
        # H) total all returns from recursion
        total += sign * A[0][fc] * sub_det 
 
    return total

In [4]:
def gauss_Jordan_eliminate(a, b, n):
    for k in range(n):
        if np.fabs(a[k,k]) < 1.0e-12:
            for i in range(k+1,n):
                if np.fabs(a[i,k]) > np.fabs(a[k,k]):
                    for j in range(k,n):
                        a[k,j],a[i,j]=a[i,j],a[k,j]
                    b[k],b[i] = b[i],b[k]
                    break
        pivot=a[k,k]
        if pivot==0:
            print("Irreverse!!!")
            break
        for j in range(k,n):
            a[k,j]/=pivot
        b[k]/=pivot
        for i in range(n):
            if i==k or a[i,k]==0:
                continue
            else:
                factor=a[i,k]
                for j in range(k,n):
                    a[i,j]-=factor*a[k,j]
                b[i]-=factor*b[k]
    return b



In [5]:
a,b,n=inputMatrix()
print("Matrix A:\n",a)
print("Inverse matrix:")
gauss_Jordan_eliminate(a,b,n)


Matrix A:
 [[ 1.  2.  5.]
 [-2.  0.  1.]
 [ 3.  1. -4.]]
Inverse matrix:


array([[ 0.04761905, -0.61904762, -0.0952381 ],
       [ 0.23809524,  0.9047619 ,  0.52380952],
       [ 0.0952381 , -0.23809524, -0.19047619]])